### ISSUE TITLE
Login/Auth issues 

### ISSUE THREAD

**Issue by kbongco** [kbongco/NookDepot#13]
Copy and paste the raw MD code of this template, then replace the quote blocks with your detailed, clear descriptions.

Unexpected Behavior
getting a 500 error. 
NoMethodError (undefined method `password_digest' for #<User:0x00007fa9d1ea1230>
Did you mean?  password):

Expected Behavior
-supposed to be able to login and get a token in local storage? 

Reproduce the Error
-Try logging in 

Include the exact error message, and if helpful, any supplemental documentation, such as screen captures.

Copy and paste the contents of the error message here.
NoMethodError (undefined method `password_digest' for #<User:0x00007fa9d1ea1230>
Did you mean?  password):

1. The tasteville repo + recordings + auth lesson 
2.  https://stackoverflow.com/questions/48138958/rails-nomethoderror-undefined-method-password-digest

**Comment by cgibsonmm** [comment]
Has this been fixed?

**Comment by kbongco** [comment]
oh my bad yeah it was lemme close it
